### ISSUE TITLE
Any plans for 1.18.2?

### ISSUE THREAD

**Issue by netcore10** [fooooooooooooooo/upc#1]
This would be ideal for my modpack.

**Comment by MSandro** [comment]
I really hope for a port.

**Comment by bvoo** [comment]
me 3

**Comment by Daturachan** [comment]
For those waiting around, I've compiled a working 1.18.2 version.
I just compiled  @fooooooooooooooo 1.18.2 branch with the latest Gradle and dependencies: I take no credit whatsoever and will gladly take my fork down if I'm asked to.

You can get it here: [https://github.com/Daturachan/upc_1.18.2/releases](https://github.com/Daturachan/upc_1.18.2/releases)

**Comment by bvoo** [comment]
that is so cool good job

**Comment by fooooooooooooooo** [comment]
still cant build 1.18.2 branch myself, I get insane rng errors that feel like gradle is using half 1.18.1 dependencies and half 1.18.2

**Comment by Daturachan** [comment]
> still cant build 1.18.2 branch myself, I get insane rng errors that feel like gradle is using half 1.18.1 dependencies and half 1.18.2

You're more than welcome to yoink my build folder if you want: [https://ufile.io/ajvzm78w](https://ufile.io/ajvzm78w)

I'm using Gradle 7.4.2 btw.

**Comment by netcore10** [comment]
> For those waiting around, I've compiled a working 1.18.2 version. I just compiled @fooooooooooooooo 1.18.2 branch with the latest Gradle and dependencies: I take no credit whatsoever and will gladly take my fork down if I'm asked to.
> 
> You can get it here: https://github.com/Daturachan/upc_1.18.2/releases

nice! Now i just need to wait for it to catch up on curse so i can add it to modpacks.

**Comment by fooooooooooooooo** [comment]
merged 206e95e741a16e2b8d805ce553090af0a294cdab
